### ISSUE TITLE
Fix for quirky 403 error if anyone has it

### ISSUE THREAD

**Issue by lihuelworks** [Tueska/fl-HowLongToBeat#4]
I just had a 403 error using this pluggin, and reading on https://github.com/ckatzorke/howlongtobeat/pull/54, it apparently had something to do with some funky user-agent shenanigans on the original HowLongToBeat API Wrapper, which this plugin takes from. 

Anyway if someone has Flow Launcher crash because of it, I've solved it by adding this line at line 81-91 of `dist\main\hltbsearch.js`

```
try {
                let result = yield axios.post(HltbSearch.SEARCH_URL, search, {
                    headers: {
                        'User-Agent': new UserAgent().toString(), 👈🏻👈🏻 ADDED THIS LINE HERE
                        'content-type': 'application/json',
                        'origin': 'https://howlongtobeat.com/',
                        'referer': 'https://howlongtobeat.com/'
                    },
                    timeout: 20000,
                    signal,
                });

```

Also, I want to apologize for the dev for having to get a notification for this poorly written not-an-issue, but it's 1 a.m here and I don't even know how to start to help fix this bug, or if even exists outside of my cursed machine. Anywho tksm for the plugin, love it to death. Too bad you can only star it once.

**Comment by Tueska** [comment]
Thank you for notifying me about this issue, I actually haven't got around to playing games in a while, hence using the Plugin. Turns out that the error is replicable on every machine, at least that I had access to :)

I've updated the dependencies, and now it seems to be working again.
→ Fixed in [1.0.1](https://github.com/Tueska/fl-HowLongToBeat/releases/tag/v1.0.1)

It's already up-to-date in the FlowLauncher Plugin Manifest. It should appear in the next few hours within FlowLauncher with `pm update`
